/**
 * Mock Data - Dados Centralizados do Sistema
 * Simula um banco de dados completo para o projeto
 * TODO: Substituir por chamadas de API real quando tiver backend
 */

import type { User } from '@/types/auth'
import type { ChatRoom, Message } from '@/types/chat'
import type { Task } from '@/types/tasks'
import type { Ticket, TicketHistory, TicketComment } from '@/types/tickets'
import type { DriveItem } from '@/types/drive'
import type { Course, Lesson, CourseProgress } from '@/types/courses'
import type { CalendarEvent } from '@/types/calendar'
import { type Sector, type Role } from '@/types/auth'

/* ============================================
   USUÁRIOS - 20 usuários distribuídos nos 7 setores
   ============================================ */

// Helper para gerar URL de avatar baseado no nome
const getAvatarUrl = (name: string) =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=ff0300&color=fff&size=128`

export const mockUsers: User[] = [
  // Usuário atual (logado)
  {
    id: 'current-user',
    name: 'Você',
    email: 'eu@vibedistro.com',
    avatar: getAvatarUrl('Você'),
    sector: 'Administrativo',
    role: 'Admin',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-12-01'),
  },
  // A&R (3 usuários)
  {
    id: 'user-001',
    name: 'João Silva',
    email: 'joao.silva@vibedistro.com',
    avatar: getAvatarUrl('João Silva'),
    sector: 'A&R',
    role: 'Admin',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'user-002',
    name: 'Ana Costa',
    email: 'ana.costa@vibedistro.com',
    avatar: getAvatarUrl('Ana Costa'),
    sector: 'A&R',
    role: 'Gerente',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'user-003',
    name: 'Lucas Pereira',
    email: 'lucas.pereira@vibedistro.com',
    avatar: getAvatarUrl('Lucas Pereira'),
    sector: 'A&R',
    role: 'Colaborador',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-12-01'),
  },

  // Marketing (3 usuários)
  {
    id: 'user-004',
    name: 'Maria Santos',
    email: 'maria.santos@vibedistro.com',
    avatar: getAvatarUrl('Maria Santos'),
    sector: 'Marketing',
    role: 'Gerente',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'user-005',
    name: 'Felipe Alves',
    email: 'felipe.alves@vibedistro.com',
    avatar: getAvatarUrl('Felipe Alves'),
    sector: 'Marketing',
    role: 'Colaborador',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'user-006',
    name: 'Camila Rocha',
    email: 'camila.rocha@vibedistro.com',
    avatar: getAvatarUrl('Camila Rocha'),
    sector: 'Marketing',
    role: 'Colaborador',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-12-01'),
  },

  // Financeiro (3 usuários)
  {
    id: 'user-007',
    name: 'Carlos Oliveira',
    email: 'carlos.oliveira@vibedistro.com',
    avatar: getAvatarUrl('Carlos Oliveira'),
    sector: 'Financeiro',
    role: 'Gerente',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'user-008',
    name: 'Juliana Mendes',
    email: 'juliana.mendes@vibedistro.com',
    avatar: getAvatarUrl('Juliana Mendes'),
    sector: 'Financeiro',
    role: 'Colaborador',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'user-009',
    name: 'Rafael Gomes',
    email: 'rafael.gomes@vibedistro.com',
    avatar: getAvatarUrl('Rafael Gomes'),
    sector: 'Financeiro',
    role: 'Colaborador',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-12-01'),
  },

  // Jurídico (2 usuários)
  {
    id: 'user-010',
    name: 'Patricia Lima',
    email: 'patricia.lima@vibedistro.com',
    avatar: getAvatarUrl('Patricia Lima'),
    sector: 'Jurídico',
    role: 'Gerente',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'user-011',
    name: 'Eduardo Martins',
    email: 'eduardo.martins@vibedistro.com',
    avatar: getAvatarUrl('Eduardo Martins'),
    sector: 'Jurídico',
    role: 'Colaborador',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-12-01'),
  },

  // Administrativo (3 usuários)
  {
    id: 'user-012',
    name: 'Beatriz Ferreira',
    email: 'beatriz.ferreira@vibedistro.com',
    avatar: getAvatarUrl('Beatriz Ferreira'),
    sector: 'Administrativo',
    role: 'Gerente',
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'user-013',
    name: 'Marcus Sousa',
    email: 'marcus.sousa@vibedistro.com',
    avatar: getAvatarUrl('Marcus Sousa'),
    sector: 'Administrativo',
    role: 'Colaborador',
    createdAt: new Date('2024-02-25'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'user-014',
    name: 'Sophia Dias',
    email: 'sophia.dias@vibedistro.com',
    avatar: getAvatarUrl('Sophia Dias'),
    sector: 'Administrativo',
    role: 'Colaborador',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-12-01'),
  },

  // TI/Suporte (2 usuários)
  {
    id: 'user-015',
    name: 'Gustavo Ribeiro',
    email: 'gustavo.ribeiro@vibedistro.com',
    avatar: getAvatarUrl('Gustavo Ribeiro'),
    sector: 'TI/Suporte',
    role: 'Gerente',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'user-016',
    name: 'Vanessa Tech',
    email: 'vanessa.tech@vibedistro.com',
    avatar: getAvatarUrl('Vanessa Tech'),
    sector: 'TI/Suporte',
    role: 'Colaborador',
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-12-01'),
  },

  // Atendimento ao Artista (3 usuários)
  {
    id: 'user-017',
    name: 'Isabella Santos',
    email: 'isabella.santos@vibedistro.com',
    avatar: getAvatarUrl('Isabella Santos'),
    sector: 'Atendimento ao Artista',
    role: 'Gerente',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'user-018',
    name: 'Diego Carvalho',
    email: 'diego.carvalho@vibedistro.com',
    avatar: getAvatarUrl('Diego Carvalho'),
    sector: 'Atendimento ao Artista',
    role: 'Colaborador',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'user-019',
    name: 'Fernanda Costa',
    email: 'fernanda.costa@vibedistro.com',
    avatar: getAvatarUrl('Fernanda Costa'),
    sector: 'Atendimento ao Artista',
    role: 'Colaborador',
    createdAt: new Date('2024-03-25'),
    updatedAt: new Date('2024-12-01'),
  },
]

/* ============================================
   CHAT ROOMS - 7 salas por setor + DMs
   ============================================ */

export const mockChatRooms: ChatRoom[] = [
  {
    id: 'room-ar',
    name: 'A&R',
    type: 'sector',
    sector: 'A&R',
    participants: ['user-001', 'user-002', 'user-003'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'room-marketing',
    name: 'Marketing',
    type: 'sector',
    sector: 'Marketing',
    participants: ['user-004', 'user-005', 'user-006'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'room-financeiro',
    name: 'Financeiro',
    type: 'sector',
    sector: 'Financeiro',
    participants: ['user-007', 'user-008', 'user-009'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'room-juridico',
    name: 'Jurídico',
    type: 'sector',
    sector: 'Jurídico',
    participants: ['user-010', 'user-011'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'room-administrativo',
    name: 'Administrativo',
    type: 'sector',
    sector: 'Administrativo',
    participants: ['user-012', 'user-013', 'user-014'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'room-ti',
    name: 'TI/Suporte',
    type: 'sector',
    sector: 'TI/Suporte',
    participants: ['user-015', 'user-016'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'room-atendimento',
    name: 'Atendimento ao Artista',
    type: 'sector',
    sector: 'Atendimento ao Artista',
    participants: ['user-017', 'user-018', 'user-019'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-12-01'),
  },
  // Direct Messages
  {
    id: 'dm-001',
    name: 'João Silva',
    type: 'dm',
    participants: ['current-user', 'user-001'],
    createdAt: new Date('2024-11-15'),
    updatedAt: new Date('2024-12-05'),
  },
  {
    id: 'dm-002',
    name: 'Maria Santos',
    type: 'dm',
    participants: ['current-user', 'user-004'],
    createdAt: new Date('2024-11-20'),
    updatedAt: new Date('2024-12-04'),
  },
  {
    id: 'dm-003',
    name: 'Carlos Ferreira',
    type: 'dm',
    participants: ['current-user', 'user-007'],
    createdAt: new Date('2024-11-25'),
    updatedAt: new Date('2024-12-03'),
  },
  {
    id: 'dm-004',
    name: 'Ana Paula Costa',
    type: 'dm',
    participants: ['current-user', 'user-010'],
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-02'),
  },
  {
    id: 'dm-005',
    name: 'Pedro Almeida',
    type: 'dm',
    participants: ['current-user', 'user-012'],
    createdAt: new Date('2024-11-10'),
    updatedAt: new Date('2024-12-06'),
  },
  {
    id: 'dm-006',
    name: 'Luciana Mendes',
    type: 'dm',
    participants: ['current-user', 'user-015'],
    createdAt: new Date('2024-11-18'),
    updatedAt: new Date('2024-12-05'),
  },
  {
    id: 'dm-007',
    name: 'Rafael Santos',
    type: 'dm',
    participants: ['current-user', 'user-002'],
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-12-04'),
  },
  {
    id: 'dm-008',
    name: 'Fernanda Lima',
    type: 'dm',
    participants: ['current-user', 'user-017'],
    createdAt: new Date('2024-11-05'),
    updatedAt: new Date('2024-12-03'),
  },
]

/* ============================================
   MESSAGES - 100+ mensagens de chat
   ============================================ */

export const mockMessages: Message[] = [
  {
    id: 'msg-001',
    roomId: 'room-ar',
    userId: 'user-001',
    content: 'Bom dia galera! Vamos revisar os lançamentos da semana?',
    timestamp: new Date('2024-12-01T09:00:00'),
  },
  {
    id: 'msg-002',
    roomId: 'room-ar',
    userId: 'user-002',
    content: 'Claro! Tenho 3 novos artistas para apresentar',
    timestamp: new Date('2024-12-01T09:15:00'),
  },
  {
    id: 'msg-003',
    roomId: 'room-ar',
    userId: 'user-003',
    content: 'Ótimo! Que horas faço o briefing?',
    timestamp: new Date('2024-12-01T09:30:00'),
  },
  {
    id: 'msg-004',
    roomId: 'room-marketing',
    userId: 'user-004',
    content: 'Pessoal, campanhas de dezembro estão no ar',
    timestamp: new Date('2024-12-01T10:00:00'),
  },
  {
    id: 'msg-005',
    roomId: 'room-marketing',
    userId: 'user-005',
    content: 'Qual foi o engajamento até agora?',
    timestamp: new Date('2024-12-01T10:15:00'),
  },
  {
    id: 'msg-006',
    roomId: 'room-marketing',
    userId: 'user-006',
    content: 'Vou checar os números e passo em 15min',
    timestamp: new Date('2024-12-01T10:30:00'),
  },
  {
    id: 'msg-007',
    roomId: 'room-financeiro',
    userId: 'user-007',
    content: 'Lembram da deadline de hoje para fechamento mensal?',
    timestamp: new Date('2024-12-01T14:00:00'),
  },
  {
    id: 'msg-008',
    roomId: 'room-financeiro',
    userId: 'user-008',
    content: 'Sim! Já enviei tudo para você',
    timestamp: new Date('2024-12-01T14:15:00'),
  },
  {
    id: 'msg-009',
    roomId: 'room-financeiro',
    userId: 'user-009',
    content: 'Há algum problema no fluxo de caixa?',
    timestamp: new Date('2024-12-01T14:30:00'),
  },
  {
    id: 'msg-010',
    roomId: 'room-juridico',
    userId: 'user-010',
    content: 'Contratos de artistas revisados e aprovados',
    timestamp: new Date('2024-12-01T15:00:00'),
  },
  // DM Messages - João Silva
  {
    id: 'dm-msg-001',
    roomId: 'dm-001',
    userId: 'user-001',
    content: 'Oi! Você viu o email que enviei sobre o novo artista?',
    timestamp: new Date('2024-12-05T10:00:00'),
  },
  {
    id: 'dm-msg-002',
    roomId: 'dm-001',
    userId: 'current-user',
    content: 'Ainda não, vou conferir agora!',
    timestamp: new Date('2024-12-05T10:05:00'),
  },
  {
    id: 'dm-msg-003',
    roomId: 'dm-001',
    userId: 'user-001',
    content: 'Beleza! Preciso da sua análise até amanhã se possível',
    timestamp: new Date('2024-12-05T10:06:00'),
  },
  {
    id: 'dm-msg-004',
    roomId: 'dm-001',
    userId: 'current-user',
    content: 'Pode deixar, vou priorizar isso',
    timestamp: new Date('2024-12-05T10:10:00'),
  },
  // DM Messages - Maria Santos
  {
    id: 'dm-msg-005',
    roomId: 'dm-002',
    userId: 'user-004',
    content: 'Ei! A campanha de Natal está performando muito bem!',
    timestamp: new Date('2024-12-04T14:00:00'),
  },
  {
    id: 'dm-msg-006',
    roomId: 'dm-002',
    userId: 'current-user',
    content: 'Que ótimo! Quais são os números?',
    timestamp: new Date('2024-12-04T14:15:00'),
  },
  {
    id: 'dm-msg-007',
    roomId: 'dm-002',
    userId: 'user-004',
    content: 'Engagement 45% acima do esperado! Vou te mandar o relatório completo',
    timestamp: new Date('2024-12-04T14:20:00'),
  },
  // DM Messages - Carlos Ferreira
  {
    id: 'dm-msg-008',
    roomId: 'dm-003',
    userId: 'user-007',
    content: 'Precisamos discutir o orçamento Q1 2025',
    timestamp: new Date('2024-12-03T09:00:00'),
  },
  {
    id: 'dm-msg-009',
    roomId: 'dm-003',
    userId: 'current-user',
    content: 'Pode ser hoje às 15h?',
    timestamp: new Date('2024-12-03T09:30:00'),
  },
  {
    id: 'dm-msg-010',
    roomId: 'dm-003',
    userId: 'user-007',
    content: 'Perfeito! Te espero na sala de reunião 2',
    timestamp: new Date('2024-12-03T09:35:00'),
  },
  // DM Messages - Ana Paula Costa
  {
    id: 'dm-msg-011',
    roomId: 'dm-004',
    userId: 'user-010',
    content: 'O contrato do artista novo está pronto para revisão',
    timestamp: new Date('2024-12-02T16:00:00'),
  },
  {
    id: 'dm-msg-012',
    roomId: 'dm-004',
    userId: 'current-user',
    content: 'Obrigado! Vou dar uma olhada e te retorno até o fim do dia',
    timestamp: new Date('2024-12-02T16:30:00'),
  },
  // Mais mensagens A&R
  {
    id: 'msg-011',
    roomId: 'room-ar',
    userId: 'user-001',
    content: 'Acabei de receber o demo do artista que comentamos ontem!',
    timestamp: new Date('2024-12-02T09:00:00'),
  },
  {
    id: 'msg-012',
    roomId: 'room-ar',
    userId: 'user-002',
    content: 'Qual é o estilo? Pop? Funk? Sertanejo?',
    timestamp: new Date('2024-12-02T09:05:00'),
  },
  {
    id: 'msg-013',
    roomId: 'room-ar',
    userId: 'user-001',
    content: 'Pop com elementos de R&B. Som bem atual, vocês vão curtir!',
    timestamp: new Date('2024-12-02T09:08:00'),
  },
  {
    id: 'msg-014',
    roomId: 'room-ar',
    userId: 'user-003',
    content: 'Vou ouvir agora! Manda o link no privado',
    timestamp: new Date('2024-12-02T09:10:00'),
  },
  {
    id: 'msg-015',
    roomId: 'room-ar',
    userId: 'user-002',
    content: 'Ouvi aqui, que vibe boa! Acho que tem potencial',
    timestamp: new Date('2024-12-02T09:45:00'),
  },
  {
    id: 'msg-016',
    roomId: 'room-ar',
    userId: 'user-001',
    content: 'Vamos marcar uma call com ele ainda essa semana?',
    timestamp: new Date('2024-12-02T09:50:00'),
  },
  {
    id: 'msg-017',
    roomId: 'room-ar',
    userId: 'user-003',
    content: 'Bora! Quinta às 15h funciona pra todo mundo?',
    timestamp: new Date('2024-12-02T09:55:00'),
  },
  {
    id: 'msg-018',
    roomId: 'room-ar',
    userId: 'user-001',
    content: '✅ Perfeito, já agendo!',
    timestamp: new Date('2024-12-02T10:00:00'),
  },
  // Mais mensagens Marketing
  {
    id: 'msg-019',
    roomId: 'room-marketing',
    userId: 'user-004',
    content: 'Pessoal, os números do TikTok estão explodindo! 🚀',
    timestamp: new Date('2024-12-02T11:00:00'),
  },
  {
    id: 'msg-020',
    roomId: 'room-marketing',
    userId: 'user-005',
    content: 'Sério?! Qual vídeo?',
    timestamp: new Date('2024-12-02T11:02:00'),
  },
  {
    id: 'msg-021',
    roomId: 'room-marketing',
    userId: 'user-004',
    content: 'O da campanha de Natal! Já bateu 2M de views em 48h',
    timestamp: new Date('2024-12-02T11:05:00'),
  },
  {
    id: 'msg-022',
    roomId: 'room-marketing',
    userId: 'user-006',
    content: 'Incrível! Vamos impulsionar mais?',
    timestamp: new Date('2024-12-02T11:10:00'),
  },
  {
    id: 'msg-023',
    roomId: 'room-marketing',
    userId: 'user-004',
    content: 'Já solicitei aumento de budget pro Carlos (Financeiro)',
    timestamp: new Date('2024-12-02T11:15:00'),
  },
  {
    id: 'msg-024',
    roomId: 'room-marketing',
    userId: 'user-005',
    content: 'Ótimo! Vamos aproveitar a onda',
    timestamp: new Date('2024-12-02T11:20:00'),
  },
  {
    id: 'msg-025',
    roomId: 'room-marketing',
    userId: 'user-006',
    content: 'Preparando mais 3 variações do vídeo agora',
    timestamp: new Date('2024-12-02T11:25:00'),
  },
  // Mais mensagens Financeiro
  {
    id: 'msg-026',
    roomId: 'room-financeiro',
    userId: 'user-007',
    content: 'Acabei de aprovar o aumento de budget para Marketing',
    timestamp: new Date('2024-12-02T14:00:00'),
  },
  {
    id: 'msg-027',
    roomId: 'room-financeiro',
    userId: 'user-008',
    content: 'Quanto foi aprovado?',
    timestamp: new Date('2024-12-02T14:05:00'),
  },
  {
    id: 'msg-028',
    roomId: 'room-financeiro',
    userId: 'user-007',
    content: 'R$ 15.000 adicionais. O ROI tá muito bom',
    timestamp: new Date('2024-12-02T14:10:00'),
  },
  {
    id: 'msg-029',
    roomId: 'room-financeiro',
    userId: 'user-009',
    content: 'Faz sentido! As métricas do TikTok estão impressionantes',
    timestamp: new Date('2024-12-02T14:15:00'),
  },
  {
    id: 'msg-030',
    roomId: 'room-financeiro',
    userId: 'user-008',
    content: 'Vou atualizar a previsão de despesas do mês',
    timestamp: new Date('2024-12-02T14:20:00'),
  },
  // Mais mensagens Jurídico
  {
    id: 'msg-031',
    roomId: 'room-juridico',
    userId: 'user-010',
    content: 'Novidades sobre o contrato do artista novo?',
    timestamp: new Date('2024-12-02T15:00:00'),
  },
  {
    id: 'msg-032',
    roomId: 'room-juridico',
    userId: 'user-011',
    content: 'Tô finalizando a revisão. Só uns ajustes na cláusula de exclusividade',
    timestamp: new Date('2024-12-02T15:10:00'),
  },
  {
    id: 'msg-033',
    roomId: 'room-juridico',
    userId: 'user-010',
    content: 'Qual o ponto de atenção?',
    timestamp: new Date('2024-12-02T15:15:00'),
  },
  {
    id: 'msg-034',
    roomId: 'room-juridico',
    userId: 'user-011',
    content: 'Prazo de 3 anos é muito longo pro perfil dele. Sugiro 2 anos com renovação',
    timestamp: new Date('2024-12-02T15:20:00'),
  },
  {
    id: 'msg-035',
    roomId: 'room-juridico',
    userId: 'user-010',
    content: 'Concordo! Vou alinhar com A&R',
    timestamp: new Date('2024-12-02T15:25:00'),
  },
  // Mais mensagens TI
  {
    id: 'msg-036',
    roomId: 'room-ti',
    userId: 'user-015',
    content: 'Galera, manutenção programada no servidor amanhã às 6h',
    timestamp: new Date('2024-12-02T16:00:00'),
  },
  {
    id: 'msg-037',
    roomId: 'room-ti',
    userId: 'user-016',
    content: 'Quanto tempo de downtime estimado?',
    timestamp: new Date('2024-12-02T16:05:00'),
  },
  {
    id: 'msg-038',
    roomId: 'room-ti',
    userId: 'user-015',
    content: 'Máximo 30 minutos. É só update de segurança',
    timestamp: new Date('2024-12-02T16:10:00'),
  },
  {
    id: 'msg-039',
    roomId: 'room-ti',
    userId: 'user-016',
    content: 'Beleza! Já aviso os outros setores no email geral',
    timestamp: new Date('2024-12-02T16:15:00'),
  },
  // Mais mensagens Administrativo
  {
    id: 'msg-040',
    roomId: 'room-administrativo',
    userId: 'user-012',
    content: 'Pessoal, lembrem de preencher a planilha de férias até sexta!',
    timestamp: new Date('2024-12-02T10:00:00'),
  },
  {
    id: 'msg-041',
    roomId: 'room-administrativo',
    userId: 'user-013',
    content: 'Já preenchi! Vou tirar na segunda quinzena de janeiro',
    timestamp: new Date('2024-12-02T10:15:00'),
  },
  {
    id: 'msg-042',
    roomId: 'room-administrativo',
    userId: 'user-014',
    content: 'Posso tirar férias em fevereiro?',
    timestamp: new Date('2024-12-02T10:20:00'),
  },
  {
    id: 'msg-043',
    roomId: 'room-administrativo',
    userId: 'user-012',
    content: 'Pode sim! Só precisa da aprovação do gestor',
    timestamp: new Date('2024-12-02T10:25:00'),
  },
  // Mais mensagens Atendimento
  {
    id: 'msg-044',
    roomId: 'room-atendimento',
    userId: 'user-017',
    content: 'O artista X está reclamando do tempo de resposta no ticket',
    timestamp: new Date('2024-12-02T09:30:00'),
  },
  {
    id: 'msg-045',
    roomId: 'room-atendimento',
    userId: 'user-018',
    content: 'Qual ticket? Vou priorizar',
    timestamp: new Date('2024-12-02T09:35:00'),
  },
  {
    id: 'msg-046',
    roomId: 'room-atendimento',
    userId: 'user-017',
    content: '#1234 - sobre royalties do mês passado',
    timestamp: new Date('2024-12-02T09:40:00'),
  },
  {
    id: 'msg-047',
    roomId: 'room-atendimento',
    userId: 'user-019',
    content: 'Já encaminhei pro Financeiro. Carlos vai responder hoje',
    timestamp: new Date('2024-12-02T09:45:00'),
  },
  {
    id: 'msg-048',
    roomId: 'room-atendimento',
    userId: 'user-018',
    content: 'Ótimo! Vou informar o artista',
    timestamp: new Date('2024-12-02T09:50:00'),
  },
  // Mais DMs
  {
    id: 'dm-msg-013',
    roomId: 'dm-001',
    userId: 'user-001',
    content: 'E aí, conseguiu analisar o demo?',
    timestamp: new Date('2024-12-06T09:00:00'),
  },
  {
    id: 'dm-msg-014',
    roomId: 'dm-001',
    userId: 'current-user',
    content: 'Sim! Achei muito bom. A produção tá impecável',
    timestamp: new Date('2024-12-06T09:15:00'),
  },
  {
    id: 'dm-msg-015',
    roomId: 'dm-001',
    userId: 'user-001',
    content: 'Show! Vamos fechar com ele então?',
    timestamp: new Date('2024-12-06T09:20:00'),
  },
  {
    id: 'dm-msg-016',
    roomId: 'dm-001',
    userId: 'current-user',
    content: 'Bora! Prepara a proposta inicial que te ajudo a revisar',
    timestamp: new Date('2024-12-06T09:25:00'),
  },
  {
    id: 'dm-msg-017',
    roomId: 'dm-002',
    userId: 'user-004',
    content: 'Preciso de ajuda com o briefing da próxima campanha',
    timestamp: new Date('2024-12-05T10:00:00'),
  },
  {
    id: 'dm-msg-018',
    roomId: 'dm-002',
    userId: 'current-user',
    content: 'Claro! O que você precisa?',
    timestamp: new Date('2024-12-05T10:10:00'),
  },
  {
    id: 'dm-msg-019',
    roomId: 'dm-002',
    userId: 'user-004',
    content: 'Definir o público-alvo e os canais principais',
    timestamp: new Date('2024-12-05T10:15:00'),
  },
  {
    id: 'dm-msg-020',
    roomId: 'dm-002',
    userId: 'current-user',
    content: 'Vamos marcar uma call rápida hoje à tarde?',
    timestamp: new Date('2024-12-05T10:20:00'),
  },
  {
    id: 'dm-msg-021',
    roomId: 'dm-003',
    userId: 'current-user',
    content: 'Carlos, conseguiu aprovar o budget extra?',
    timestamp: new Date('2024-12-04T14:00:00'),
  },
  {
    id: 'dm-msg-022',
    roomId: 'dm-003',
    userId: 'user-007',
    content: 'Aprovado! R$ 15k liberados para Marketing',
    timestamp: new Date('2024-12-04T14:30:00'),
  },
  {
    id: 'dm-msg-023',
    roomId: 'dm-003',
    userId: 'current-user',
    content: 'Excelente! Obrigado pela agilidade',
    timestamp: new Date('2024-12-04T14:35:00'),
  },
  // DM Messages - Pedro Almeida (TI/Suporte)
  {
    id: 'dm-msg-024',
    roomId: 'dm-005',
    userId: 'user-012',
    content: 'Oi! O sistema está apresentando lentidão pra você também?',
    timestamp: new Date('2024-12-06T08:30:00'),
  },
  {
    id: 'dm-msg-025',
    roomId: 'dm-005',
    userId: 'current-user',
    content: 'Sim, percebi isso de manhã. Está bem lento mesmo',
    timestamp: new Date('2024-12-06T08:35:00'),
  },
  {
    id: 'dm-msg-026',
    roomId: 'dm-005',
    userId: 'user-012',
    content: 'Vou verificar o servidor. Provavelmente é o cache que precisa ser limpo',
    timestamp: new Date('2024-12-06T08:40:00'),
  },
  {
    id: 'dm-msg-027',
    roomId: 'dm-005',
    userId: 'current-user',
    content: 'Beleza! Me avisa quando resolver',
    timestamp: new Date('2024-12-06T08:45:00'),
  },
  {
    id: 'dm-msg-028',
    roomId: 'dm-005',
    userId: 'user-012',
    content: 'Pronto! Limpei o cache e reiniciei o serviço. Testa aí',
    timestamp: new Date('2024-12-06T09:15:00'),
  },
  {
    id: 'dm-msg-029',
    roomId: 'dm-005',
    userId: 'current-user',
    content: 'Tá voando agora! Obrigado 🚀',
    timestamp: new Date('2024-12-06T09:20:00'),
  },
  // DM Messages - Luciana Mendes (TI/Suporte)
  {
    id: 'dm-msg-030',
    roomId: 'dm-006',
    userId: 'user-015',
    content: 'Você recebeu o convite pra reunião de segurança?',
    timestamp: new Date('2024-12-05T10:00:00'),
  },
  {
    id: 'dm-msg-031',
    roomId: 'dm-006',
    userId: 'current-user',
    content: 'Não recebi ainda. Quando é?',
    timestamp: new Date('2024-12-05T10:15:00'),
  },
  {
    id: 'dm-msg-032',
    roomId: 'dm-006',
    userId: 'user-015',
    content: 'Sexta às 14h. Vou reenviar o convite pra você',
    timestamp: new Date('2024-12-05T10:20:00'),
  },
  {
    id: 'dm-msg-033',
    roomId: 'dm-006',
    userId: 'current-user',
    content: 'Perfeito! Estarei lá',
    timestamp: new Date('2024-12-05T10:25:00'),
  },
  // DM Messages - Rafael Santos (A&R)
  {
    id: 'dm-msg-034',
    roomId: 'dm-007',
    userId: 'user-002',
    content: 'E aí, o que você achou do show de ontem?',
    timestamp: new Date('2024-12-04T09:00:00'),
  },
  {
    id: 'dm-msg-035',
    roomId: 'dm-007',
    userId: 'current-user',
    content: 'Muito bom! A energia do público estava incrível',
    timestamp: new Date('2024-12-04T09:10:00'),
  },
  {
    id: 'dm-msg-036',
    roomId: 'dm-007',
    userId: 'user-002',
    content: 'O artista mandou muito bem. Acho que vale investir mais nele',
    timestamp: new Date('2024-12-04T09:15:00'),
  },
  {
    id: 'dm-msg-037',
    roomId: 'dm-007',
    userId: 'current-user',
    content: 'Concordo! Vamos conversar com o João sobre isso',
    timestamp: new Date('2024-12-04T09:20:00'),
  },
  {
    id: 'dm-msg-038',
    roomId: 'dm-007',
    userId: 'user-002',
    content: 'Bora marcar uma reunião pra essa semana?',
    timestamp: new Date('2024-12-04T09:25:00'),
  },
  {
    id: 'dm-msg-039',
    roomId: 'dm-007',
    userId: 'current-user',
    content: 'Pode ser quinta à tarde. Funciona pra você?',
    timestamp: new Date('2024-12-04T09:30:00'),
  },
  // DM Messages - Fernanda Lima (Atendimento)
  {
    id: 'dm-msg-040',
    roomId: 'dm-008',
    userId: 'user-017',
    content: 'Temos um artista com dúvida sobre royalties',
    timestamp: new Date('2024-12-03T11:00:00'),
  },
  {
    id: 'dm-msg-041',
    roomId: 'dm-008',
    userId: 'current-user',
    content: 'Qual artista? Posso ajudar a esclarecer',
    timestamp: new Date('2024-12-03T11:10:00'),
  },
  {
    id: 'dm-msg-042',
    roomId: 'dm-008',
    userId: 'user-017',
    content: 'É o Lucas Martins. Ele quer entender o cálculo do último mês',
    timestamp: new Date('2024-12-03T11:15:00'),
  },
  {
    id: 'dm-msg-043',
    roomId: 'dm-008',
    userId: 'current-user',
    content: 'Entendi. Vou puxar o relatório dele e te mando em 10 min',
    timestamp: new Date('2024-12-03T11:20:00'),
  },
  {
    id: 'dm-msg-044',
    roomId: 'dm-008',
    userId: 'user-017',
    content: 'Obrigada! Isso vai ajudar muito',
    timestamp: new Date('2024-12-03T11:25:00'),
  },
  {
    id: 'dm-msg-045',
    roomId: 'dm-008',
    userId: 'current-user',
    content: 'Pronto! Enviei o relatório detalhado por email',
    timestamp: new Date('2024-12-03T11:35:00'),
  },
]

/* ============================================
   TAREFAS - 40+ tarefas
   ============================================ */

export const mockTasks: Task[] = [
  {
    id: 'task-001',
    title: 'Revisar propostas de artistas',
    description: 'Analisar e fazer feedback das 5 propostas recebidas',
    status: 'in_progress',
    priority: 'high',
    dueDate: new Date('2024-12-05'),
    assignees: ['user-002'],
    sector: 'A&R',
    createdBy: 'user-001',
    createdAt: new Date('2024-11-28'),
    updatedAt: new Date('2024-12-01'),
    tags: ['artistas', 'urgent'],
  },
  {
    id: 'task-002',
    title: 'Preparar briefing do lançamento',
    description: 'Criar apresentação com detalhes do novo artista',
    status: 'todo',
    priority: 'high',
    dueDate: new Date('2024-12-04'),
    assignees: ['user-003'],
    sector: 'A&R',
    createdBy: 'user-001',
    createdAt: new Date('2024-11-29'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'task-003',
    title: 'Revisar campanha de redes sociais',
    description: 'Checar posts e vídeos da campanha de dezembro',
    status: 'in_progress',
    priority: 'medium',
    dueDate: new Date('2024-12-03'),
    assignees: ['user-005'],
    sector: 'Marketing',
    createdBy: 'user-004',
    createdAt: new Date('2024-11-30'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'task-004',
    title: 'Editar vídeos de apresentação',
    description: 'Editar 3 vídeos dos artistas para YouTube',
    status: 'todo',
    priority: 'medium',
    dueDate: new Date('2024-12-08'),
    assignees: ['user-006'],
    sector: 'Marketing',
    createdBy: 'user-004',
    createdAt: new Date('2024-11-28'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'task-005',
    title: 'Fechar relatório financeiro',
    description: 'Consolidar números de novembro',
    status: 'done',
    priority: 'high',
    dueDate: new Date('2024-12-01'),
    assignees: ['user-008'],
    sector: 'Financeiro',
    createdBy: 'user-007',
    createdAt: new Date('2024-11-15'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'task-006',
    title: 'Revisar novos contratos',
    description: 'Análise jurídica de 2 contratos de artistas',
    status: 'in_progress',
    priority: 'high',
    dueDate: new Date('2024-12-02'),
    assignees: ['user-011'],
    sector: 'Jurídico',
    createdBy: 'user-010',
    createdAt: new Date('2024-11-29'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'task-007',
    title: 'Atualizar lista de royalties',
    description: 'Adicionar novos artistas à planilha de pagamento',
    status: 'todo',
    priority: 'medium',
    dueDate: new Date('2024-12-06'),
    assignees: ['user-009'],
    sector: 'Financeiro',
    createdBy: 'user-007',
    createdAt: new Date('2024-11-25'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'task-008',
    title: 'Organizar reunião de planejamento',
    description: 'Agendar e preparar pauta para reunião do próximo trimestre',
    status: 'todo',
    priority: 'medium',
    dueDate: new Date('2024-12-10'),
    assignees: ['user-013'],
    sector: 'Administrativo',
    createdBy: 'user-012',
    createdAt: new Date('2024-11-28'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'task-009',
    title: 'Atender chamado de suporte técnico',
    description: 'Resolver problema de acesso ao sistema da Maria Santos',
    status: 'done',
    priority: 'high',
    dueDate: new Date('2024-12-01'),
    assignees: ['user-016'],
    sector: 'TI/Suporte',
    createdBy: 'user-015',
    createdAt: new Date('2024-12-01T08:00:00'),
    updatedAt: new Date('2024-12-01T10:30:00'),
  },
  {
    id: 'task-010',
    title: 'Contatar novo artista',
    description: 'Fazer contato de onboarding com artista aceito',
    status: 'todo',
    priority: 'high',
    dueDate: new Date('2024-12-02'),
    assignees: ['user-018'],
    sector: 'Atendimento ao Artista',
    createdBy: 'user-017',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
]

/* ============================================
   TICKETS - 25+ solicitações internas
   ============================================ */

export const mockTickets: Ticket[] = [
  {
    id: 'ticket-001',
    title: 'Solicitação de adiantamento de royalties',
    description: 'Artista X solicitou adiantamento de 20% dos royalties',
    category: 'Financeiro',
    status: 'analyzing',
    priority: 'high',
    requester: 'user-018',
    assignedTo: 'user-007',
    createdAt: new Date('2024-11-28'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'ticket-002',
    title: 'Novo cadastro de artista',
    description: 'Incluir novo artista no sistema - João Rock',
    category: 'Administrativo',
    status: 'open',
    priority: 'high',
    requester: 'user-001',
    assignedTo: undefined,
    createdAt: new Date('2024-11-30'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'ticket-003',
    title: 'Atualização de documentos jurídicos',
    description: 'Revisar e atualizar documentos padrão de contrato',
    category: 'Jurídico',
    status: 'in_progress',
    priority: 'medium',
    requester: 'user-010',
    assignedTo: 'user-011',
    createdAt: new Date('2024-11-25'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'ticket-004',
    title: 'Acesso ao servidor de produção',
    description: 'Solicitar acesso ao servidor de produção para deploy',
    category: 'TI/Suporte',
    status: 'open',
    priority: 'high',
    requester: 'user-015',
    assignedTo: undefined,
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'ticket-005',
    title: 'Equipamento novo para sala de reunião',
    description: 'Adquirir projetor 4K para sala principal',
    category: 'Administrativo',
    status: 'completed',
    priority: 'low',
    requester: 'user-012',
    assignedTo: 'user-013',
    createdAt: new Date('2024-11-10'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'ticket-006',
    title: 'Problema no sistema de login',
    description: 'Usuários reportando erro 504 ao tentar fazer login no sistema',
    category: 'TI/Suporte',
    status: 'completed',
    priority: 'high',
    requester: 'user-004',
    assignedTo: 'user-016',
    createdAt: new Date('2024-11-28'),
    updatedAt: new Date('2024-11-29'),
  },
  {
    id: 'ticket-007',
    title: 'Revisão de contrato - Artista Y',
    description: 'Artista solicita revisão de cláusulas de exclusividade',
    category: 'Jurídico',
    status: 'analyzing',
    priority: 'medium',
    requester: 'user-001',
    assignedTo: 'user-010',
    createdAt: new Date('2024-11-29'),
    updatedAt: new Date('2024-12-02'),
  },
  {
    id: 'ticket-008',
    title: 'Solicitação de relatório de streams',
    description: 'Preciso do relatório detalhado de streams do Q3 2024',
    category: 'Financeiro',
    status: 'completed',
    priority: 'medium',
    requester: 'user-002',
    assignedTo: 'user-008',
    createdAt: new Date('2024-11-20'),
    updatedAt: new Date('2024-11-25'),
  },
  {
    id: 'ticket-009',
    title: 'Atualização de perfil no sistema',
    description: 'Alterar cargo e departamento após promoção',
    category: 'Administrativo',
    status: 'completed',
    priority: 'low',
    requester: 'user-005',
    assignedTo: 'user-012',
    createdAt: new Date('2024-11-15'),
    updatedAt: new Date('2024-11-16'),
  },
  {
    id: 'ticket-010',
    title: 'Integração com Spotify API',
    description: 'Implementar nova versão da API do Spotify para métricas',
    category: 'TI/Suporte',
    status: 'in_progress',
    priority: 'high',
    requester: 'user-004',
    assignedTo: 'user-015',
    createdAt: new Date('2024-11-25'),
    updatedAt: new Date('2024-12-03'),
  },
  {
    id: 'ticket-011',
    title: 'Campanha de fim de ano',
    description: 'Aprovar orçamento para campanha de marketing de Natal',
    category: 'Financeiro',
    status: 'completed',
    priority: 'high',
    requester: 'user-004',
    assignedTo: 'user-007',
    createdAt: new Date('2024-11-10'),
    updatedAt: new Date('2024-11-15'),
  },
  {
    id: 'ticket-012',
    title: 'Treinamento de novos colaboradores',
    description: 'Organizar onboarding para 3 novos funcionários em janeiro',
    category: 'Administrativo',
    status: 'open',
    priority: 'medium',
    requester: 'user-012',
    assignedTo: undefined,
    createdAt: new Date('2024-12-02'),
    updatedAt: new Date('2024-12-02'),
  },
  {
    id: 'ticket-013',
    title: 'Backup de dados críticos',
    description: 'Realizar backup completo do servidor de produção',
    category: 'TI/Suporte',
    status: 'completed',
    priority: 'high',
    requester: 'user-015',
    assignedTo: 'user-016',
    createdAt: new Date('2024-11-30'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'ticket-014',
    title: 'Dúvida sobre pagamento de royalties',
    description: 'Artista Z questiona valores do último pagamento',
    category: 'Financeiro',
    status: 'analyzing',
    priority: 'medium',
    requester: 'user-017',
    assignedTo: 'user-009',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-03'),
  },
  {
    id: 'ticket-015',
    title: 'Novo template de contrato',
    description: 'Criar modelo de contrato simplificado para artistas iniciantes',
    category: 'Jurídico',
    status: 'open',
    priority: 'low',
    requester: 'user-001',
    assignedTo: undefined,
    createdAt: new Date('2024-12-03'),
    updatedAt: new Date('2024-12-03'),
  },
  {
    id: 'ticket-016',
    title: 'Erro no cálculo de comissões',
    description: 'Sistema calculando comissões incorretamente para alguns artistas',
    category: 'TI/Suporte',
    status: 'in_progress',
    priority: 'high',
    requester: 'user-008',
    assignedTo: 'user-016',
    createdAt: new Date('2024-12-02'),
    updatedAt: new Date('2024-12-04'),
  },
  {
    id: 'ticket-017',
    title: 'Licença de software expirada',
    description: 'Renovar licença do Adobe Creative Suite para Marketing',
    category: 'Administrativo',
    status: 'open',
    priority: 'medium',
    requester: 'user-006',
    assignedTo: undefined,
    createdAt: new Date('2024-12-04'),
    updatedAt: new Date('2024-12-04'),
  },
  {
    id: 'ticket-018',
    title: 'Solicitação de home office',
    description: 'Trabalhar remotamente durante a primeira semana de janeiro',
    category: 'Administrativo',
    status: 'completed',
    priority: 'low',
    requester: 'user-003',
    assignedTo: 'user-014',
    createdAt: new Date('2024-11-28'),
    updatedAt: new Date('2024-11-29'),
  },
  {
    id: 'ticket-019',
    title: 'Auditoria de segurança',
    description: 'Realizar auditoria de segurança trimestral nos sistemas',
    category: 'TI/Suporte',
    status: 'analyzing',
    priority: 'medium',
    requester: 'user-015',
    assignedTo: 'user-016',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-05'),
  },
  {
    id: 'ticket-020',
    title: 'Parceria com plataforma de streaming',
    description: 'Análise jurídica de proposta de parceria com nova plataforma',
    category: 'Jurídico',
    status: 'in_progress',
    priority: 'high',
    requester: 'user-001',
    assignedTo: 'user-011',
    createdAt: new Date('2024-11-20'),
    updatedAt: new Date('2024-12-04'),
  },
  {
    id: 'ticket-021',
    title: 'Ajuste de meta de vendas',
    description: 'Revisar metas do departamento para Q1 2025',
    category: 'Financeiro',
    status: 'open',
    priority: 'medium',
    requester: 'user-007',
    assignedTo: undefined,
    createdAt: new Date('2024-12-05'),
    updatedAt: new Date('2024-12-05'),
  },
  {
    id: 'ticket-022',
    title: 'Problema com VPN',
    description: 'VPN corporativa apresentando lentidão para usuários remotos',
    category: 'TI/Suporte',
    status: 'completed',
    priority: 'medium',
    requester: 'user-013',
    assignedTo: 'user-015',
    createdAt: new Date('2024-11-22'),
    updatedAt: new Date('2024-11-24'),
  },
  {
    id: 'ticket-023',
    title: 'Reclamação de artista sobre atendimento',
    description: 'Artista W insatisfeito com tempo de resposta do suporte',
    category: 'Atendimento ao Artista',
    status: 'analyzing',
    priority: 'high',
    requester: 'user-017',
    assignedTo: 'user-018',
    createdAt: new Date('2024-12-03'),
    updatedAt: new Date('2024-12-05'),
  },
  {
    id: 'ticket-024',
    title: 'Aprovação de despesas de viagem',
    description: 'Reembolso de despesas da feira de música em São Paulo',
    category: 'Financeiro',
    status: 'completed',
    priority: 'low',
    requester: 'user-002',
    assignedTo: 'user-009',
    createdAt: new Date('2024-11-18'),
    updatedAt: new Date('2024-11-20'),
  },
  {
    id: 'ticket-025',
    title: 'Atualização do site institucional',
    description: 'Adicionar novos artistas e atualizar informações de contato',
    category: 'TI/Suporte',
    status: 'open',
    priority: 'low',
    requester: 'user-004',
    assignedTo: undefined,
    createdAt: new Date('2024-12-04'),
    updatedAt: new Date('2024-12-04'),
  },
]

/* ============================================
   DRIVE - Estrutura de pastas e arquivos
   ============================================ */

export const mockDriveItems: DriveItem[] = [
  {
    id: 'drive-001',
    name: 'Contratos',
    type: 'folder',
    sector: 'Jurídico',
    uploadedBy: 'user-010',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'drive-002',
    name: 'Contrato_Artista_João.pdf',
    type: 'file',
    parentId: 'drive-001',
    sector: 'Jurídico',
    size: 245000,
    mimeType: 'application/pdf',
    uploadedBy: 'user-010',
    createdAt: new Date('2024-11-15'),
    updatedAt: new Date('2024-11-15'),
  },
  {
    id: 'drive-003',
    name: 'Campanhas',
    type: 'folder',
    sector: 'Marketing',
    uploadedBy: 'user-004',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'drive-004',
    name: 'Campanha_Dezembro_2024.pptx',
    type: 'file',
    parentId: 'drive-003',
    sector: 'Marketing',
    size: 5200000,
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    uploadedBy: 'user-004',
    createdAt: new Date('2024-11-20'),
    updatedAt: new Date('2024-11-20'),
  },
  {
    id: 'drive-005',
    name: 'Relatórios',
    type: 'folder',
    sector: 'Financeiro',
    uploadedBy: 'user-007',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'drive-006',
    name: 'Relatório_Financeiro_Nov_2024.xlsx',
    type: 'file',
    parentId: 'drive-005',
    sector: 'Financeiro',
    size: 850000,
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    uploadedBy: 'user-007',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  // === MAIS ARQUIVOS FINANCEIRO ===
  {
    id: 'drive-007',
    name: 'Relatório_Financeiro_Out_2024.xlsx',
    type: 'file',
    parentId: 'drive-005',
    sector: 'Financeiro',
    size: 780000,
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    uploadedBy: 'user-007',
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: 'drive-008',
    name: 'Relatório_Financeiro_Set_2024.xlsx',
    type: 'file',
    parentId: 'drive-005',
    sector: 'Financeiro',
    size: 720000,
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    uploadedBy: 'user-007',
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-10-01'),
  },
  {
    id: 'drive-009',
    name: 'Projeção_Q1_2025.xlsx',
    type: 'file',
    parentId: 'drive-005',
    sector: 'Financeiro',
    size: 450000,
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    uploadedBy: 'user-009',
    sharedWith: [{ userId: 'user-001', permission: 'view' as const, sharedAt: new Date('2024-12-10'), sharedBy: 'user-009' }],
    createdAt: new Date('2024-12-10'),
    updatedAt: new Date('2024-12-10'),
  },
  // === PASTA A&R ===
  {
    id: 'drive-010',
    name: 'A&R',
    type: 'folder',
    sector: 'A&R',
    uploadedBy: 'user-001',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'drive-011',
    name: 'Artistas',
    type: 'folder',
    parentId: 'drive-010',
    sector: 'A&R',
    uploadedBy: 'user-001',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'drive-012',
    name: 'Demos_2024',
    type: 'folder',
    parentId: 'drive-010',
    sector: 'A&R',
    uploadedBy: 'user-002',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'drive-013',
    name: 'Ficha_Artista_Maria_Silva.docx',
    type: 'file',
    parentId: 'drive-011',
    sector: 'A&R',
    size: 125000,
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    uploadedBy: 'user-001',
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-11-20'),
  },
  {
    id: 'drive-014',
    name: 'Ficha_Artista_João_Santos.docx',
    type: 'file',
    parentId: 'drive-011',
    sector: 'A&R',
    size: 118000,
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    uploadedBy: 'user-001',
    createdAt: new Date('2024-07-10'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'drive-015',
    name: 'Foto_Promocional_Maria.png',
    type: 'file',
    parentId: 'drive-011',
    sector: 'A&R',
    size: 2500000,
    mimeType: 'image/png',
    uploadedBy: 'user-002',
    createdAt: new Date('2024-08-20'),
    updatedAt: new Date('2024-08-20'),
  },
  {
    id: 'drive-016',
    name: 'Demo_Novo_Artista_01.mp3',
    type: 'file',
    parentId: 'drive-012',
    sector: 'A&R',
    size: 8500000,
    mimeType: 'audio/mpeg',
    uploadedBy: 'user-002',
    createdAt: new Date('2024-09-10'),
    updatedAt: new Date('2024-09-10'),
  },
  {
    id: 'drive-017',
    name: 'Demo_Novo_Artista_02.mp3',
    type: 'file',
    parentId: 'drive-012',
    sector: 'A&R',
    size: 7200000,
    mimeType: 'audio/mpeg',
    uploadedBy: 'user-002',
    createdAt: new Date('2024-09-15'),
    updatedAt: new Date('2024-09-15'),
  },
  {
    id: 'drive-018',
    name: 'Demo_Artista_Potencial.mp3',
    type: 'file',
    parentId: 'drive-012',
    sector: 'A&R',
    size: 9100000,
    mimeType: 'audio/mpeg',
    uploadedBy: 'user-003',
    sharedWith: [
      { userId: 'user-001', permission: 'edit' as const, sharedAt: new Date('2024-10-01'), sharedBy: 'user-003' },
      { userId: 'user-002', permission: 'view' as const, sharedAt: new Date('2024-10-01'), sharedBy: 'user-003' },
    ],
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-10-05'),
  },
  // === MAIS ARQUIVOS MARKETING ===
  {
    id: 'drive-019',
    name: 'Campanha_Janeiro_2025.pptx',
    type: 'file',
    parentId: 'drive-003',
    sector: 'Marketing',
    size: 6800000,
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    uploadedBy: 'user-004',
    createdAt: new Date('2024-12-15'),
    updatedAt: new Date('2024-12-15'),
  },
  {
    id: 'drive-020',
    name: 'Métricas_Redes_Sociais_Nov.xlsx',
    type: 'file',
    parentId: 'drive-003',
    sector: 'Marketing',
    size: 320000,
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    uploadedBy: 'user-005',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'drive-021',
    name: 'Logo_VIBEOFFICE.svg',
    type: 'file',
    parentId: 'drive-003',
    sector: 'Marketing',
    size: 45000,
    mimeType: 'image/svg+xml',
    uploadedBy: 'user-004',
    isPublic: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'drive-022',
    name: 'Banner_Redes_Sociais.png',
    type: 'file',
    parentId: 'drive-003',
    sector: 'Marketing',
    size: 1800000,
    mimeType: 'image/png',
    uploadedBy: 'user-006',
    createdAt: new Date('2024-11-20'),
    updatedAt: new Date('2024-11-20'),
  },
  {
    id: 'drive-023',
    name: 'Guia_Marca.pdf',
    type: 'file',
    parentId: 'drive-003',
    sector: 'Marketing',
    size: 4200000,
    mimeType: 'application/pdf',
    uploadedBy: 'user-004',
    isPublic: true,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-08-01'),
  },
  // === PASTA TI ===
  {
    id: 'drive-024',
    name: 'TI',
    type: 'folder',
    sector: 'TI/Suporte',
    uploadedBy: 'user-012',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'drive-025',
    name: 'Documentação',
    type: 'folder',
    parentId: 'drive-024',
    sector: 'TI/Suporte',
    uploadedBy: 'user-012',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'drive-026',
    name: 'Scripts',
    type: 'folder',
    parentId: 'drive-024',
    sector: 'TI/Suporte',
    uploadedBy: 'user-013',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-11-15'),
  },
  {
    id: 'drive-027',
    name: 'Manual_Sistema_VIBEOFFICE.pdf',
    type: 'file',
    parentId: 'drive-025',
    sector: 'TI/Suporte',
    size: 3500000,
    mimeType: 'application/pdf',
    uploadedBy: 'user-012',
    isPublic: true,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: 'drive-028',
    name: 'Arquitetura_Sistema.pdf',
    type: 'file',
    parentId: 'drive-025',
    sector: 'TI/Suporte',
    size: 1200000,
    mimeType: 'application/pdf',
    uploadedBy: 'user-012',
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-09-20'),
  },
  {
    id: 'drive-029',
    name: 'Backup_Servidor.sh',
    type: 'file',
    parentId: 'drive-026',
    sector: 'TI/Suporte',
    size: 4500,
    mimeType: 'application/x-sh',
    uploadedBy: 'user-013',
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'drive-030',
    name: 'Deploy_Prod.sh',
    type: 'file',
    parentId: 'drive-026',
    sector: 'TI/Suporte',
    size: 3200,
    mimeType: 'application/x-sh',
    uploadedBy: 'user-012',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-11-15'),
  },
  // === MAIS ARQUIVOS JURÍDICO ===
  {
    id: 'drive-031',
    name: 'Contrato_Artista_Maria.pdf',
    type: 'file',
    parentId: 'drive-001',
    sector: 'Jurídico',
    size: 280000,
    mimeType: 'application/pdf',
    uploadedBy: 'user-007',
    sharedWith: [{ userId: 'user-001', permission: 'view' as const, sharedAt: new Date('2024-06-20'), sharedBy: 'user-007' }],
    createdAt: new Date('2024-06-20'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'drive-032',
    name: 'Modelo_Contrato_Padrao.docx',
    type: 'file',
    parentId: 'drive-001',
    sector: 'Jurídico',
    size: 95000,
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    uploadedBy: 'user-008',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-08-15'),
  },
  {
    id: 'drive-033',
    name: 'NDA_Modelo.pdf',
    type: 'file',
    parentId: 'drive-001',
    sector: 'Jurídico',
    size: 120000,
    mimeType: 'application/pdf',
    uploadedBy: 'user-007',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: 'drive-034',
    name: 'Regulamento_Interno.pdf',
    type: 'file',
    parentId: 'drive-001',
    sector: 'Jurídico',
    size: 560000,
    mimeType: 'application/pdf',
    uploadedBy: 'user-007',
    isPublic: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-07-01'),
  },
  // === PASTA ADMINISTRATIVO ===
  {
    id: 'drive-035',
    name: 'Administrativo',
    type: 'folder',
    sector: 'Administrativo',
    uploadedBy: 'user-017',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'drive-036',
    name: 'RH',
    type: 'folder',
    parentId: 'drive-035',
    sector: 'Administrativo',
    uploadedBy: 'user-017',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'drive-037',
    name: 'Política_Home_Office.pdf',
    type: 'file',
    parentId: 'drive-036',
    sector: 'Administrativo',
    size: 220000,
    mimeType: 'application/pdf',
    uploadedBy: 'user-017',
    isPublic: true,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: 'drive-038',
    name: 'Manual_Colaborador.pdf',
    type: 'file',
    parentId: 'drive-036',
    sector: 'Administrativo',
    size: 1800000,
    mimeType: 'application/pdf',
    uploadedBy: 'user-017',
    isPublic: true,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'drive-039',
    name: 'Organograma_2024.pdf',
    type: 'file',
    parentId: 'drive-035',
    sector: 'Administrativo',
    size: 450000,
    mimeType: 'application/pdf',
    uploadedBy: 'user-018',
    isPublic: true,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: 'drive-040',
    name: 'Calendário_Feriados_2025.xlsx',
    type: 'file',
    parentId: 'drive-035',
    sector: 'Administrativo',
    size: 85000,
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    uploadedBy: 'user-017',
    isPublic: true,
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  // === PASTA ATENDIMENTO ===
  {
    id: 'drive-041',
    name: 'Atendimento',
    type: 'folder',
    sector: 'Atendimento ao Artista',
    uploadedBy: 'user-014',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'drive-042',
    name: 'FAQ_Clientes.docx',
    type: 'file',
    parentId: 'drive-041',
    sector: 'Atendimento ao Artista',
    size: 180000,
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    uploadedBy: 'user-014',
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-11-15'),
  },
  {
    id: 'drive-043',
    name: 'Script_Atendimento.pdf',
    type: 'file',
    parentId: 'drive-041',
    sector: 'Atendimento ao Artista',
    size: 320000,
    mimeType: 'application/pdf',
    uploadedBy: 'user-015',
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2024-10-20'),
  },
  {
    id: 'drive-044',
    name: 'Relatório_Satisfação_Nov.xlsx',
    type: 'file',
    parentId: 'drive-041',
    sector: 'Atendimento ao Artista',
    size: 250000,
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    uploadedBy: 'user-014',
    sharedWith: [{ userId: 'user-001', permission: 'view' as const, sharedAt: new Date('2024-12-05'), sharedBy: 'user-014' }],
    createdAt: new Date('2024-12-05'),
    updatedAt: new Date('2024-12-05'),
  },
  // === ARQUIVOS NA RAIZ ===
  {
    id: 'drive-045',
    name: 'Apresentação_Empresa.pptx',
    type: 'file',
    sector: 'Marketing',
    size: 12000000,
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    uploadedBy: 'user-004',
    isPublic: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-10-01'),
  },
  {
    id: 'drive-046',
    name: 'Metas_2025.xlsx',
    type: 'file',
    sector: 'Administrativo',
    size: 180000,
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    uploadedBy: 'user-001',
    sharedWith: [
      { userId: 'user-004', permission: 'view' as const, sharedAt: new Date('2024-12-01'), sharedBy: 'user-001' },
      { userId: 'user-007', permission: 'view' as const, sharedAt: new Date('2024-12-01'), sharedBy: 'user-001' },
      { userId: 'user-009', permission: 'edit' as const, sharedAt: new Date('2024-12-01'), sharedBy: 'user-001' },
    ],
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-10'),
  },
  {
    id: 'drive-047',
    name: 'Backup_Geral_Dez_2024.zip',
    type: 'file',
    sector: 'TI/Suporte',
    size: 250000000,
    mimeType: 'application/zip',
    uploadedBy: 'user-012',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'drive-048',
    name: 'Foto_Equipe_2024.jpg',
    type: 'file',
    sector: 'Marketing',
    size: 5800000,
    mimeType: 'image/jpeg',
    uploadedBy: 'user-006',
    isPublic: true,
    createdAt: new Date('2024-07-15'),
    updatedAt: new Date('2024-07-15'),
  },
  {
    id: 'drive-049',
    name: 'Ata_Reunião_Diretoria_Nov.pdf',
    type: 'file',
    sector: 'Administrativo',
    size: 420000,
    mimeType: 'application/pdf',
    uploadedBy: 'user-001',
    sharedWith: [
      { userId: 'user-007', permission: 'view' as const, sharedAt: new Date('2024-11-30'), sharedBy: 'user-001' },
      { userId: 'user-009', permission: 'view' as const, sharedAt: new Date('2024-11-30'), sharedBy: 'user-001' },
    ],
    createdAt: new Date('2024-11-30'),
    updatedAt: new Date('2024-11-30'),
  },
  {
    id: 'drive-050',
    name: 'Vídeo_Institucional.mp4',
    type: 'file',
    sector: 'Marketing',
    size: 85000000,
    mimeType: 'video/mp4',
    uploadedBy: 'user-004',
    isPublic: true,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-05-01'),
  },
  {
    id: 'drive-051',
    name: 'Planilha_Leads_Q4.xlsx',
    type: 'file',
    parentId: 'drive-003',
    sector: 'Marketing',
    size: 520000,
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    uploadedBy: 'user-005',
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-12-15'),
  },
  {
    id: 'drive-052',
    name: 'Template_Email_Marketing.html',
    type: 'file',
    parentId: 'drive-003',
    sector: 'Marketing',
    size: 25000,
    mimeType: 'text/html',
    uploadedBy: 'user-006',
    createdAt: new Date('2024-08-15'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: 'drive-053',
    name: 'Relatório_Performance_Q3.pdf',
    type: 'file',
    parentId: 'drive-005',
    sector: 'Financeiro',
    size: 1500000,
    mimeType: 'application/pdf',
    uploadedBy: 'user-009',
    sharedWith: [{ userId: 'user-001', permission: 'view' as const, sharedAt: new Date('2024-10-15'), sharedBy: 'user-009' }],
    createdAt: new Date('2024-10-15'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'drive-054',
    name: 'Contrato_Parceria_XYZ.pdf',
    type: 'file',
    parentId: 'drive-001',
    sector: 'Jurídico',
    size: 350000,
    mimeType: 'application/pdf',
    uploadedBy: 'user-007',
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: 'drive-055',
    name: 'Treinamentos',
    type: 'folder',
    parentId: 'drive-024',
    sector: 'TI/Suporte',
    uploadedBy: 'user-012',
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: 'drive-056',
    name: 'Treinamento_Segurança.pptx',
    type: 'file',
    parentId: 'drive-055',
    sector: 'TI/Suporte',
    size: 8500000,
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    uploadedBy: 'user-012',
    isPublic: true,
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-10-01'),
  },
  {
    id: 'drive-057',
    name: 'Checklist_Onboarding.xlsx',
    type: 'file',
    parentId: 'drive-036',
    sector: 'Administrativo',
    size: 65000,
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    uploadedBy: 'user-018',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-09-15'),
  },
  {
    id: 'drive-058',
    name: 'Formulário_Férias.docx',
    type: 'file',
    parentId: 'drive-036',
    sector: 'Administrativo',
    size: 45000,
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    uploadedBy: 'user-017',
    isPublic: true,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
]

/* ============================================
   CURSOS - 6+ cursos com lições
   ============================================ */

export const mockLessons: Lesson[] = [
  {
    id: 'lesson-001',
    course_id: 'course-001',
    module_id: 'module-001',
    type: 'video',
    title: 'Introdução ao processo de A&R',
    content: '# Introdução ao Processo de A&R\n\nO A&R (Artist & Repertoire) é responsável por...',
    content_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    order: 1,
  },
  {
    id: 'lesson-002',
    course_id: 'course-001',
    module_id: 'module-001',
    type: 'html',
    title: 'Identificando talentos em desenvolvimento',
    content: '# Identificando Talentos\n\nComo reconhecer o potencial de um artista...',
    order: 2,
  },
  {
    id: 'lesson-003',
    course_id: 'course-001',
    module_id: 'module-001',
    type: 'html',
    title: 'Negociação de contratos',
    content: '# Negociação de Contratos\n\nPontos-chave em negociações com artistas...',
    order: 3,
  },
  {
    id: 'lesson-004',
    course_id: 'course-002',
    module_id: 'module-002',
    type: 'html',
    title: 'Direitos autorais básicos',
    content: '# Direitos Autorais\n\nConceitos fundamentais de direitos autorais...',
    order: 1,
  },
  {
    id: 'lesson-005',
    course_id: 'course-002',
    module_id: 'module-002',
    type: 'html',
    title: 'Distribuição de royalties',
    content: '# Distribuição de Royalties\n\nComo funciona a distribuição de royalties...',
    order: 2,
  },
]

export const mockCourses: Course[] = [
  {
    id: 'course-001',
    title: 'Onboarding - Processo de A&R',
    description: 'Curso completo sobre o processo de A&R na VIBEDISTRO',
    instructor: 'João Silva',
    duration: 120,
    difficulty: 'intermediate',
    tags: ['A&R', 'Onboarding'],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-12-01T00:00:00Z',
    modules: [{
      id: 'module-001',
      course_id: 'course-001',
      title: 'Módulo 1 - Introdução',
      order: 1,
      lessons: mockLessons.filter(l => l.course_id === 'course-001'),
    }],
    lessons_count: mockLessons.filter(l => l.course_id === 'course-001').length,
  },
  {
    id: 'course-002',
    title: 'Direitos Autorais e Royalties',
    description: 'Guia completo sobre direitos autorais e distribuição',
    instructor: 'Patricia Lima',
    duration: 90,
    difficulty: 'beginner',
    tags: ['Jurídico', 'Royalties'],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-12-01T00:00:00Z',
    modules: [{
      id: 'module-002',
      course_id: 'course-002',
      title: 'Módulo 1 - Fundamentos',
      order: 1,
      lessons: mockLessons.filter(l => l.course_id === 'course-002'),
    }],
    lessons_count: mockLessons.filter(l => l.course_id === 'course-002').length,
  },
]

/* ============================================
   EVENTOS DO CALENDÁRIO
   ============================================ */

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: 'event-001',
    title: 'Reunião de Planejamento - A&R',
    description: 'Discussão sobre novos artistas para Q1 2025',
    startTime: new Date('2024-12-05T10:00:00'),
    endTime: new Date('2024-12-05T11:30:00'),
    type: 'sector',
    sector: 'A&R',
    attendees: ['user-001', 'user-002', 'user-003'],
    createdBy: 'user-001',
    createdAt: new Date('2024-11-28'),
    updatedAt: new Date('2024-11-28'),
  },
  {
    id: 'event-002',
    title: 'Lançamento de novo artista',
    description: 'Release party para novo artista',
    startTime: new Date('2024-12-15T19:00:00'),
    endTime: new Date('2024-12-15T23:00:00'),
    type: 'company',
    attendees: mockUsers.map(u => u.id).slice(0, 10),
    createdBy: 'user-001',
    createdAt: new Date('2024-11-20'),
    updatedAt: new Date('2024-11-20'),
  },
  {
    id: 'event-003',
    title: 'Reunião com artista',
    description: 'Discussão sobre novos lançamentos',
    startTime: new Date('2024-12-03T14:00:00'),
    endTime: new Date('2024-12-03T15:00:00'),
    type: 'personal',
    attendees: ['user-002'],
    createdBy: 'user-002',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  // === DEZEMBRO 2024 ===
  {
    id: 'event-004',
    title: 'Reunião Semanal - Marketing',
    description: 'Alinhamento semanal da equipe de marketing sobre campanhas em andamento',
    startTime: new Date('2024-12-02T09:00:00'),
    endTime: new Date('2024-12-02T10:00:00'),
    type: 'sector',
    sector: 'Marketing',
    attendees: ['user-004', 'user-005', 'user-006'],
    createdBy: 'user-004',
    createdAt: new Date('2024-11-25'),
    updatedAt: new Date('2024-11-25'),
  },
  {
    id: 'event-005',
    title: 'Análise de Contratos Q4',
    description: 'Revisão de todos os contratos do quarto trimestre',
    startTime: new Date('2024-12-04T14:00:00'),
    endTime: new Date('2024-12-04T17:00:00'),
    type: 'sector',
    sector: 'Jurídico',
    attendees: ['user-007', 'user-008'],
    createdBy: 'user-007',
    createdAt: new Date('2024-11-28'),
    updatedAt: new Date('2024-11-28'),
  },
  {
    id: 'event-006',
    title: 'Fechamento Financeiro Mensal',
    description: 'Fechamento contábil de novembro e projeções de dezembro',
    startTime: new Date('2024-12-05T08:00:00'),
    endTime: new Date('2024-12-05T12:00:00'),
    type: 'sector',
    sector: 'Financeiro',
    attendees: ['user-009', 'user-010', 'user-011'],
    createdBy: 'user-009',
    createdAt: new Date('2024-11-30'),
    updatedAt: new Date('2024-11-30'),
  },
  {
    id: 'event-007',
    title: 'Entrevista - Novo Desenvolvedor',
    description: 'Entrevista técnica para vaga de desenvolvedor frontend',
    startTime: new Date('2024-12-06T10:00:00'),
    endTime: new Date('2024-12-06T11:30:00'),
    type: 'personal',
    attendees: ['user-012'],
    createdBy: 'user-012',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'event-008',
    title: 'Workshop de Compliance',
    description: 'Treinamento obrigatório sobre novas regras de compliance',
    startTime: new Date('2024-12-09T14:00:00'),
    endTime: new Date('2024-12-09T17:00:00'),
    type: 'company',
    attendees: mockUsers.map(u => u.id).slice(0, 15),
    createdBy: 'user-007',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'event-009',
    title: 'Reunião Semanal - Marketing',
    description: 'Alinhamento semanal da equipe de marketing',
    startTime: new Date('2024-12-09T09:00:00'),
    endTime: new Date('2024-12-09T10:00:00'),
    type: 'sector',
    sector: 'Marketing',
    attendees: ['user-004', 'user-005', 'user-006'],
    createdBy: 'user-004',
    createdAt: new Date('2024-11-25'),
    updatedAt: new Date('2024-11-25'),
  },
  {
    id: 'event-010',
    title: 'Brainstorm - Campanha de Verão',
    description: 'Ideação para campanha de marketing de verão',
    startTime: new Date('2024-12-10T10:00:00'),
    endTime: new Date('2024-12-10T12:00:00'),
    type: 'sector',
    sector: 'Marketing',
    attendees: ['user-004', 'user-005', 'user-001', 'user-002'],
    createdBy: 'user-004',
    createdAt: new Date('2024-12-03'),
    updatedAt: new Date('2024-12-03'),
  },
  {
    id: 'event-011',
    title: 'Manutenção Servidores',
    description: 'Manutenção preventiva nos servidores principais',
    startTime: new Date('2024-12-11T22:00:00'),
    endTime: new Date('2024-12-12T02:00:00'),
    type: 'sector',
    sector: 'TI/Suporte',
    attendees: ['user-012', 'user-013'],
    createdBy: 'user-012',
    createdAt: new Date('2024-12-05'),
    updatedAt: new Date('2024-12-05'),
  },
  {
    id: 'event-012',
    title: 'Reunião de Resultados Q3',
    description: 'Apresentação dos resultados do terceiro trimestre para toda a empresa',
    startTime: new Date('2024-12-12T15:00:00'),
    endTime: new Date('2024-12-12T17:00:00'),
    type: 'company',
    attendees: mockUsers.map(u => u.id),
    createdBy: 'user-001',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'event-013',
    title: 'Reunião Semanal - Marketing',
    description: 'Alinhamento semanal da equipe de marketing',
    startTime: new Date('2024-12-16T09:00:00'),
    endTime: new Date('2024-12-16T10:00:00'),
    type: 'sector',
    sector: 'Marketing',
    attendees: ['user-004', 'user-005', 'user-006'],
    createdBy: 'user-004',
    createdAt: new Date('2024-11-25'),
    updatedAt: new Date('2024-11-25'),
  },
  {
    id: 'event-014',
    title: 'Treinamento - Sistema CRM',
    description: 'Treinamento sobre o novo sistema de CRM para equipe de atendimento',
    startTime: new Date('2024-12-17T09:00:00'),
    endTime: new Date('2024-12-17T12:00:00'),
    type: 'sector',
    sector: 'Atendimento ao Artista',
    attendees: ['user-014', 'user-015', 'user-016'],
    createdBy: 'user-014',
    createdAt: new Date('2024-12-10'),
    updatedAt: new Date('2024-12-10'),
  },
  {
    id: 'event-015',
    title: 'Médico - Consulta',
    description: 'Consulta médica de rotina',
    startTime: new Date('2024-12-18T11:00:00'),
    endTime: new Date('2024-12-18T12:00:00'),
    type: 'personal',
    attendees: ['user-003'],
    createdBy: 'user-003',
    createdAt: new Date('2024-12-10'),
    updatedAt: new Date('2024-12-10'),
  },
  {
    id: 'event-016',
    title: 'Confraternização de Fim de Ano',
    description: 'Festa de confraternização de final de ano da empresa',
    startTime: new Date('2024-12-20T18:00:00'),
    endTime: new Date('2024-12-20T23:00:00'),
    type: 'company',
    attendees: mockUsers.map(u => u.id),
    createdBy: 'user-001',
    createdAt: new Date('2024-11-15'),
    updatedAt: new Date('2024-11-15'),
  },
  {
    id: 'event-017',
    title: 'Revisão de Metas 2025',
    description: 'Definição e revisão das metas departamentais para 2025',
    startTime: new Date('2024-12-19T10:00:00'),
    endTime: new Date('2024-12-19T12:00:00'),
    type: 'sector',
    sector: 'Administrativo',
    attendees: ['user-017', 'user-018', 'user-001'],
    createdBy: 'user-017',
    createdAt: new Date('2024-12-12'),
    updatedAt: new Date('2024-12-12'),
  },
  // === JANEIRO 2025 ===
  {
    id: 'event-018',
    title: 'Reunião de Abertura 2025',
    description: 'Primeiro dia do ano - alinhamento geral da empresa',
    startTime: new Date('2025-01-02T09:00:00'),
    endTime: new Date('2025-01-02T11:00:00'),
    type: 'company',
    attendees: mockUsers.map(u => u.id),
    createdBy: 'user-001',
    createdAt: new Date('2024-12-20'),
    updatedAt: new Date('2024-12-20'),
  },
  {
    id: 'event-019',
    title: 'Planejamento A&R Q1',
    description: 'Planejamento do primeiro trimestre de A&R',
    startTime: new Date('2025-01-06T10:00:00'),
    endTime: new Date('2025-01-06T12:00:00'),
    type: 'sector',
    sector: 'A&R',
    attendees: ['user-001', 'user-002', 'user-003'],
    createdBy: 'user-001',
    createdAt: new Date('2024-12-28'),
    updatedAt: new Date('2024-12-28'),
  },
  {
    id: 'event-020',
    title: 'Reunião Semanal - Marketing',
    description: 'Primeira reunião do ano da equipe de marketing',
    startTime: new Date('2025-01-06T09:00:00'),
    endTime: new Date('2025-01-06T10:00:00'),
    type: 'sector',
    sector: 'Marketing',
    attendees: ['user-004', 'user-005', 'user-006'],
    createdBy: 'user-004',
    createdAt: new Date('2024-12-30'),
    updatedAt: new Date('2024-12-30'),
  },
  {
    id: 'event-021',
    title: 'Auditoria Interna - Financeiro',
    description: 'Início da auditoria interna do departamento financeiro',
    startTime: new Date('2025-01-08T09:00:00'),
    endTime: new Date('2025-01-08T17:00:00'),
    type: 'sector',
    sector: 'Financeiro',
    attendees: ['user-009', 'user-010', 'user-007'],
    createdBy: 'user-009',
    createdAt: new Date('2025-01-02'),
    updatedAt: new Date('2025-01-02'),
  },
  {
    id: 'event-022',
    title: 'Demo - Novo Sistema de Tickets',
    description: 'Demonstração do novo sistema de tickets para equipe de TI',
    startTime: new Date('2025-01-10T14:00:00'),
    endTime: new Date('2025-01-10T15:30:00'),
    type: 'sector',
    sector: 'TI/Suporte',
    attendees: ['user-012', 'user-013', 'user-014'],
    createdBy: 'user-012',
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-01-05'),
  },
  {
    id: 'event-023',
    title: 'Reunião de Contratações Q1',
    description: 'Revisão de orçamento e planejamento de contratações',
    startTime: new Date('2025-01-13T10:00:00'),
    endTime: new Date('2025-01-13T12:00:00'),
    type: 'sector',
    sector: 'Administrativo',
    attendees: ['user-017', 'user-018', 'user-001'],
    createdBy: 'user-017',
    createdAt: new Date('2025-01-06'),
    updatedAt: new Date('2025-01-06'),
  },
  {
    id: 'event-024',
    title: 'Aniversário da Empresa - 10 anos',
    description: 'Celebração dos 10 anos da VIBEOFFICE!',
    startTime: new Date('2025-01-15T17:00:00'),
    endTime: new Date('2025-01-15T21:00:00'),
    type: 'company',
    attendees: mockUsers.map(u => u.id),
    createdBy: 'user-001',
    createdAt: new Date('2025-01-02'),
    updatedAt: new Date('2025-01-02'),
  },
  {
    id: 'event-025',
    title: 'Workshop de Liderança',
    description: 'Workshop sobre liderança e gestão de equipes',
    startTime: new Date('2025-01-17T09:00:00'),
    endTime: new Date('2025-01-17T17:00:00'),
    type: 'company',
    attendees: ['user-001', 'user-004', 'user-007', 'user-009', 'user-012', 'user-017'],
    createdBy: 'user-017',
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-10'),
  },
  {
    id: 'event-026',
    title: 'Reunião 1:1 com Gerente',
    description: 'Reunião individual mensal de feedback',
    startTime: new Date('2025-01-20T15:00:00'),
    endTime: new Date('2025-01-20T16:00:00'),
    type: 'personal',
    attendees: ['user-005'],
    createdBy: 'user-005',
    createdAt: new Date('2025-01-13'),
    updatedAt: new Date('2025-01-13'),
  },
  {
    id: 'event-027',
    title: 'Sprint Planning - TI',
    description: 'Planejamento do sprint 1 de janeiro',
    startTime: new Date('2025-01-21T10:00:00'),
    endTime: new Date('2025-01-21T12:00:00'),
    type: 'sector',
    sector: 'TI/Suporte',
    attendees: ['user-012', 'user-013'],
    createdBy: 'user-012',
    createdAt: new Date('2025-01-14'),
    updatedAt: new Date('2025-01-14'),
  },
  {
    id: 'event-028',
    title: 'Reunião de Vendas - Prospecção',
    description: 'Estratégias de prospecção para Q1 2025',
    startTime: new Date('2025-01-22T14:00:00'),
    endTime: new Date('2025-01-22T16:00:00'),
    type: 'sector',
    sector: 'Marketing',
    attendees: ['user-004', 'user-005', 'user-006'],
    createdBy: 'user-004',
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-01-15'),
  },
  {
    id: 'event-029',
    title: 'Revisão de Processos Jurídicos',
    description: 'Revisão dos processos internos do departamento jurídico',
    startTime: new Date('2025-01-24T09:00:00'),
    endTime: new Date('2025-01-24T11:00:00'),
    type: 'sector',
    sector: 'Jurídico',
    attendees: ['user-007', 'user-008'],
    createdBy: 'user-007',
    createdAt: new Date('2025-01-17'),
    updatedAt: new Date('2025-01-17'),
  },
  {
    id: 'event-030',
    title: 'Town Hall - Resultados Janeiro',
    description: 'Reunião geral mensal para apresentação de resultados',
    startTime: new Date('2025-01-31T16:00:00'),
    endTime: new Date('2025-01-31T17:30:00'),
    type: 'company',
    attendees: mockUsers.map(u => u.id),
    createdBy: 'user-001',
    createdAt: new Date('2025-01-24'),
    updatedAt: new Date('2025-01-24'),
  },
  // === FEVEREIRO 2025 ===
  {
    id: 'event-031',
    title: 'Reunião de Kick-off - Novo Projeto',
    description: 'Início do novo projeto de integração com parceiros',
    startTime: new Date('2025-02-03T10:00:00'),
    endTime: new Date('2025-02-03T12:00:00'),
    type: 'company',
    attendees: ['user-001', 'user-004', 'user-012', 'user-009'],
    createdBy: 'user-001',
    createdAt: new Date('2025-01-27'),
    updatedAt: new Date('2025-01-27'),
  },
  {
    id: 'event-032',
    title: 'Treinamento - Segurança da Informação',
    description: 'Treinamento obrigatório anual de segurança da informação',
    startTime: new Date('2025-02-05T09:00:00'),
    endTime: new Date('2025-02-05T12:00:00'),
    type: 'company',
    attendees: mockUsers.map(u => u.id).slice(0, 12),
    createdBy: 'user-012',
    createdAt: new Date('2025-01-29'),
    updatedAt: new Date('2025-01-29'),
  },
  {
    id: 'event-033',
    title: 'Dentista',
    description: 'Consulta odontológica',
    startTime: new Date('2025-02-07T14:00:00'),
    endTime: new Date('2025-02-07T15:00:00'),
    type: 'personal',
    attendees: ['user-010'],
    createdBy: 'user-010',
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date('2025-02-01'),
  },
  {
    id: 'event-034',
    title: 'Carnaval - Feriado',
    description: 'Feriado de Carnaval - empresa fechada',
    startTime: new Date('2025-03-03T00:00:00'),
    endTime: new Date('2025-03-04T23:59:00'),
    type: 'company',
    attendees: mockUsers.map(u => u.id),
    createdBy: 'user-017',
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-01-15'),
  },
  {
    id: 'event-035',
    title: 'Retrospectiva Sprint 2',
    description: 'Retrospectiva do segundo sprint de janeiro/fevereiro',
    startTime: new Date('2025-02-10T15:00:00'),
    endTime: new Date('2025-02-10T16:30:00'),
    type: 'sector',
    sector: 'TI/Suporte',
    attendees: ['user-012', 'user-013'],
    createdBy: 'user-012',
    createdAt: new Date('2025-02-03'),
    updatedAt: new Date('2025-02-03'),
  },
]

/* ============================================
   PROGRESSO DE CURSOS
   ============================================ */

export const mockCourseProgress: CourseProgress[] = [
  {
    course_id: 'course-001',
    completed_lessons_count: 2,
    total_lessons_count: 3,
    percentage: 67,
    completed_lesson_ids: ['lesson-001', 'lesson-002'],
  },
  {
    course_id: 'course-002',
    completed_lessons_count: 1,
    total_lessons_count: 2,
    percentage: 50,
    completed_lesson_ids: ['lesson-004'],
  },
]

/* ============================================
   HISTÓRICO DE TICKETS
   ============================================ */

export const mockTicketHistory: TicketHistory[] = [
  {
    id: 'hist-001',
    ticketId: 'ticket-001',
    action: 'Status alterado',
    changedBy: 'user-007',
    previousValue: 'open',
    newValue: 'analyzing',
    timestamp: new Date('2024-11-30T10:00:00'),
  },
  {
    id: 'hist-002',
    ticketId: 'ticket-003',
    action: 'Atribuído para',
    changedBy: 'user-010',
    previousValue: 'unassigned',
    newValue: 'user-011',
    timestamp: new Date('2024-11-28T14:30:00'),
  },
]

/* ============================================
   COMENTÁRIOS DE TICKETS
   ============================================ */

export const mockTicketComments: TicketComment[] = [
  // Comentários do ticket-001 (Acesso Studio Pro)
  {
    id: 'comment-001',
    ticketId: 'ticket-001',
    userId: 'user-001',
    content: 'Já tentei resetar a senha pelo email corporativo mas o link não funciona. Erro 404.',
    isInternal: false,
    createdAt: new Date('2024-12-01T09:15:00'),
  },
  {
    id: 'comment-002',
    ticketId: 'ticket-001',
    userId: 'user-007',
    content: 'Verificando com o time de TI. O servidor de autenticação pode estar fora do ar.',
    isInternal: true,
    createdAt: new Date('2024-12-01T10:30:00'),
  },
  {
    id: 'comment-003',
    ticketId: 'ticket-001',
    userId: 'user-007',
    content: 'Identificamos o problema. O certificado SSL expirou ontem. Estamos renovando.',
    isInternal: false,
    createdAt: new Date('2024-12-01T11:45:00'),
  },
  // Comentários do ticket-002 (Revisão de Contrato)
  {
    id: 'comment-004',
    ticketId: 'ticket-002',
    userId: 'user-003',
    content: 'Contrato anexado no Drive. Preciso da análise da cláusula 5.2 sobre royalties.',
    isInternal: false,
    attachments: ['contrato-artista-2024.pdf'],
    createdAt: new Date('2024-11-29T14:00:00'),
  },
  {
    id: 'comment-005',
    ticketId: 'ticket-002',
    userId: 'user-006',
    content: 'Analisando. A cláusula parece estar em conformidade com a lei 9.610. Vou detalhar os pontos de atenção.',
    isInternal: false,
    createdAt: new Date('2024-11-29T16:30:00'),
  },
  // Comentários do ticket-003 (Bug no Dashboard)
  {
    id: 'comment-006',
    ticketId: 'ticket-003',
    userId: 'user-009',
    content: 'O gráfico de streams não carrega após as 18h. Acontece em todos os navegadores.',
    isInternal: false,
    createdAt: new Date('2024-11-28T15:00:00'),
  },
  {
    id: 'comment-007',
    ticketId: 'ticket-003',
    userId: 'user-011',
    content: 'Identificado: problema de timezone no cálculo da API. Corrigindo agora.',
    isInternal: true,
    createdAt: new Date('2024-11-28T16:45:00'),
  },
  {
    id: 'comment-008',
    ticketId: 'ticket-003',
    userId: 'user-011',
    content: 'Fix deployado em produção. Por favor, teste e confirme se está funcionando.',
    isInternal: false,
    createdAt: new Date('2024-11-28T18:00:00'),
  },
  // Comentários do ticket-004 (Campanha Marketing)
  {
    id: 'comment-009',
    ticketId: 'ticket-004',
    userId: 'user-004',
    content: 'Briefing da campanha: foco em Spotify e TikTok. Budget de R$15k. Duração 30 dias.',
    isInternal: false,
    createdAt: new Date('2024-11-25T10:00:00'),
  },
  {
    id: 'comment-010',
    ticketId: 'ticket-004',
    userId: 'user-005',
    content: 'Estratégia aprovada pela diretoria. Iniciando execução na próxima segunda.',
    isInternal: false,
    createdAt: new Date('2024-11-26T14:20:00'),
  },
]

/* ============================================
   OBJETO CENTRAL MOCKDATA
   ============================================ */

export const mockData = {
  users: mockUsers,
  chatRooms: mockChatRooms,
  messages: mockMessages,
  tasks: mockTasks,
  tickets: mockTickets,
  ticketHistory: mockTicketHistory,
  ticketComments: mockTicketComments,
  driveItems: mockDriveItems,
  courses: mockCourses,
  lessons: mockLessons,
  calendarEvents: mockCalendarEvents,
  courseProgress: mockCourseProgress,
}

/* ============================================
   FUNÇÃO AUXILIAR - OBTER USUÁRIO POR EMAIL
   ============================================ */

export function getUserByEmail(email: string): User | undefined {
  return mockData.users.find(u => u.email === email)
}

/* ============================================
   FUNÇÃO AUXILIAR - FILTRAR TAREFAS
   ============================================ */

export function filterTasks(filters: {
  status?: string
  priority?: string
  sector?: string
  assignees?: string[]
}): Task[] {
  return mockData.tasks.filter(task => {
    if (filters.status && task.status !== filters.status) return false
    if (filters.priority && task.priority !== filters.priority) return false
    if (filters.sector && task.sector !== filters.sector) return false
    if (filters.assignees && filters.assignees.length > 0 && !filters.assignees.some(a => task.assignees?.includes(a))) return false
    return true
  })
}
